name: "Build a custom Fedora bootc image"

env:
  IMAGE_NAME: "fedora-laptop"
  REGISTRY: "quay.io/acardace"
  IMAGE_TAG: "latest"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'Containerfile.bootc'
      - 'config.toml'
      - 'etc/**'
      - 'usr/**'
      - 'rpms/**'
      - '.github/workflows/image.yml'
  push:
    branches:
      - main
    paths:
      - 'Containerfile.bootc'
      - 'config.toml'
      - 'etc/**'
      - 'usr/**'
      - 'rpms/**'
      - '.github/workflows/image.yml'
  schedule:
    - cron:  '0 0 * * 0'

permissions: read-all

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-push-image:
    runs-on: [self-hosted, buildah]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install buildah
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y buildah
          buildah version

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }} ${{ github.sha }}
          containerfiles: Containerfile.bootc
          layers: true
          oci: true

      - name: Push to Quay.io
        uses: redhat-actions/push-to-registry@v2
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_PASSWORD }}
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}
          tags: ${{ env.IMAGE_TAG }} ${{ github.sha }}
