name: "Build a custom Fedora bootc image"

env:
  IMAGE_NAME: "fedora-laptop"
  REGISTRY: "ghcr.io/acardace"
  IMAGE_TAG: "kde"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - kde
    paths:
      - 'Containerfile'
      - 'config.toml'
      - 'etc/**'
      - 'usr/**'
      - 'rpms/**'
      - '.github/workflows/image.yml'
  push:
    branches:
      - kde
    paths:
      - 'Containerfile'
      - 'config.toml'
      - 'etc/**'
      - 'usr/**'
      - 'rpms/**'
      - '.github/workflows/image.yml'
  schedule:
    - cron:  '0 0 * * 0'

permissions:
  contents: read
  packages: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: matrix.arch == 'arm64'

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}-${{ matrix.arch }}
          containerfiles: Containerfile
          platforms: linux/${{ matrix.arch }}
          layers: true
          oci: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/kde'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push arch image to GHCR
        uses: redhat-actions/push-to-registry@v2
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/kde'
        with:
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}
          tags: ${{ env.IMAGE_TAG }}-${{ matrix.arch }}

  manifest:
    runs-on: ubuntu-latest
    needs: build
    if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/kde'
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          buildah manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          buildah manifest add ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-amd64
          buildah manifest add ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-arm64
          buildah manifest push --all ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
